# Generated by Django 3.2.8 on 2022-08-29 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biketable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model', models.CharField(default='', max_length=200)),
                ('Year', models.CharField(default='', max_length=200)),
                ('Category', models.CharField(default='', max_length=200)),
                ('Rating', models.CharField(default='', max_length=200)),
                ('Displacement', models.CharField(default='', max_length=200)),
                ('Engine_type', models.CharField(default='', max_length=200)),
                ('Power', models.CharField(default='', max_length=200)),
                ('Top_speed', models.CharField(default='', max_length=200)),
                ('Fuel_system', models.CharField(default='', max_length=200)),
                ('Cooling_system', models.CharField(default='', max_length=200)),
                ('Gearbox', models.CharField(default='', max_length=200)),
                ('Transmission_type', models.CharField(default='', max_length=200)),
                ('Clutch', models.CharField(default='', max_length=200)),
                ('Fuel_consumption', models.CharField(default='', max_length=200)),
                ('Greenhouse_gases', models.CharField(default='', max_length=200)),
                ('Frame_type', models.CharField(default='', max_length=200)),
                ('Front_suspension', models.CharField(default='', max_length=200)),
                ('Rear_suspension', models.CharField(default='', max_length=200)),
                ('Front_tire', models.CharField(default='', max_length=200)),
                ('Rear_tire', models.CharField(default='', max_length=200)),
                ('Front_brakes', models.CharField(default='', max_length=200)),
                ('Rear_brakes', models.CharField(default='', max_length=200)),
                ('Dry_weight', models.CharField(default='', max_length=200)),
                ('Power_weight_ratio', models.CharField(default='', max_length=200)),
                ('Seat_height', models.CharField(default='', max_length=200)),
                ('Overall_height', models.CharField(default='', max_length=200)),
                ('Overall_length', models.CharField(default='', max_length=200)),
                ('Overall_width', models.CharField(default='', max_length=200)),
                ('Wheelbase', models.CharField(default='', max_length=200)),
                ('Fuel_capacity', models.CharField(default='', max_length=200)),
                ('Color_options', models.CharField(default='', max_length=200)),
                ('Starter', models.CharField(default='', max_length=200)),
                ('Factory_warranty', models.CharField(default='', max_length=200)),
                ('Comments', models.CharField(default='', max_length=200)),
                ('Update_specs', models.CharField(default='', max_length=200)),
                ('Insurance_costs', models.CharField(default='', max_length=200)),
                ('Finance_options', models.CharField(default='', max_length=200)),
                ('Parts_finder', models.CharField(default='', max_length=200)),
                ('Maintenance', models.CharField(default='', max_length=200)),
                ('Ask_questions', models.CharField(default='', max_length=200)),
                ('Related_bikes', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bikeimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('alt', models.TextField(max_length=140)),
                ('postId', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.blog')),
            ],
        ),
    ]
