# Generated by Django 3.2.8 on 2022-08-29 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeimage',
            name='postId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
    ]
