# Generated by Django 3.2.8 on 2022-08-29 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_bikeimage_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='table',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='blog.biketable'),
        ),
    ]
