# Generated by Django 3.2.8 on 2022-08-29 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20220829_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='table',
        ),
        migrations.AddField(
            model_name='biketable',
            name='idofblog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='table_blogs', to='blog.blog'),
        ),
    ]
