# Generated by Django 3.2.8 on 2022-08-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20220829_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blogcategory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='bloguser',
            new_name='user',
        ),
    ]
