# Generated by Django 3.2.8 on 2022-09-01 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='category',
            new_name='blog_category',
        ),
        migrations.AlterField(
            model_name='biketable',
            name='idofblog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_blogs', to='blog.blog'),
        ),
        migrations.AlterField(
            model_name='page',
            name='banner',
            field=models.ImageField(null=True, upload_to='blog_banners'),
        ),
    ]
