# Generated by Django 3.2.8 on 2022-09-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20220901_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='slug',
            new_name='blogslug',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='blogslug',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='blogpost',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='comment',
            new_name='blogcomment',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='slug',
            new_name='blogslug',
        ),
    ]
