# Generated by Django 3.2.8 on 2022-09-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20220901_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blogslug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='blogslug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='blogpost',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='blogcomment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='blogslug',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='biketable',
            name='idofblog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='table_blogs', to='blog.blog'),
        ),
    ]
