# Generated by Django 3.2.8 on 2022-09-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20220901_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='isupdated',
            field=models.IntegerField(choices=[(0, 'Updated'), (1, 'Not updated')], default=0),
        ),
    ]
