# Generated by Django 3.2.8 on 2022-08-29 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0004_bikeimage_biketable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('noOfPost', models.IntegerField(default=0)),
                ('modelLink', models.URLField(default=0, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Extracted')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(default=0, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Extracted')], default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lastChecked', models.DateTimeField(auto_now_add=True)),
                ('modelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Extract.model')),
                ('postId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.blog')),
            ],
        ),
    ]
