# Generated by Django 3.2.8 on 2022-09-01 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20220901_2030'),
        ('Extract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='postId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blog'),
        ),
    ]
