# Generated by Django 3.2.8 on 2022-09-19 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_category_slug'),
        ('Extract', '0002_alter_url_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='modelLink',
            field=models.URLField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='link',
            field=models.URLField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='postId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blog'),
        ),
    ]
